Repository LetsStreamIt/frontend-service, pull requests merged in 2024-10, with the labels that each got.

#114 Synch video play stop
  src/components/session/video/SessionFrame.vue
Labels: enhancement

#133 Fix Login redirection
  src/router/index.js
Labels: bug

#151 fix: popup closure
  src/components/session/CreateSessionPopup.vue
Labels: bug

#159 fix: video autoplay by muting the video when joining
  src/components/session/video/SessionFrame.vue
Labels: bug

#161 fix: chat message username and scrolling
  src/components/session/chat/SessionChat.vue
  src/components/session/chat/message/TextMessageComponent.vue
Labels: bug

#177 fix: error on logout
  src/components/common/navbar/CollapsableNavbar.vue
  src/components/common/navbar/NavbarContainer.vue
  src/middlewares/apiClient.ts
  src/stores/auth.ts
Labels: bug

#180 Fix infinite loop in login check
  src/middlewares/apiClient.ts
  src/stores/auth.ts
Labels: bug

#179 Update readme
  CONTRIBUTING.md
  README.md
Labels: documentation
